### ISSUE TITLE
Data_question

### ISSUE THREAD

**Issue by zhangbeining777** [YihaoAng/TSGBench#1]
I downloaded your code,but I couldn't find data and preprocessed data.I really need these preprocessed data.

**Comment by YihaoAng** [comment]
Hello. Thank you for reaching out and expressing interest in our work!

As we mentioned in the paper, the datasets are all publicly available. In particular, we provide the link to these datasets at https://github.com/YihaoAng/TSGBench#datasets for your reference.

In addition, we recommend referring to the source publications of these datasets cited in Table 3 for more details.

Thank you.
