### ISSUE TITLE
Error when running preprocessing code

### ISSUE THREAD

**Issue by xylhal** [YihaoAng/TSGBench#2]
Hi, 

I'm trying to replicate your results and I am running into multiple problems.

I downloaded the traffic data, unzipped and placed it into the `/data` folder.

When I run `python preprocessing/data_preprocess.py`, I got the following error:

> Traceback (most recent call last):
>   File "preprocessing/data_preprocess.py", line 55, in <module>
>     ori_data = np.loadtxt('./DATASET_NAME.csv', delimiter = ",",skiprows = 1)
>     raise FileNotFoundError(f"{path} not found.")
> FileNotFoundError: ./DATASET_NAME.csv not found.

Am I missing certain steps or could you provide a much more detail instructions? For example, is there suppose to be a .csv file somewhere with the names of the datasets?

Also, the packages version in the provided `requirements.txt` might be outdated as I faced multiple conflicts when trying to install them and had to manually resolve the conflicts.

**Comment by YihaoAng** [comment]
Hello. Thank you for reaching out and expressing interest in our work!

To resolve the error, please ensure the following:

- Replace DATASET_NAME in the code with the actual name of your dataset file.
- Confirm the data format matches what the script expects (e.g., csv) and comment the lines for other formats.

Thank you.
